In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
import folium
from folium.plugins import HeatMap
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',None)
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_rows', None)

In [46]:
df= pd.read_csv("C:/Users/akrit/Downloads/employee_experience_survey_data.csv")

In [47]:
df

,Name,Age Bracket,Gender,Ethnicity,Job Title,Department,Date Survey Completed,Job Satisfaction,Work-Life Balance,Management Support,Team Collaboration,Workload Fairness,Career Development Opportunities,Workplace Inclusivity,Company Communication,Compensation Satisfaction,Job Security,Overall Engagement
0,John Doe,25-34,Female,Asian,Product Manager,Product Development,2024-10-05,Disagree,Strongly Agree,Neutral,Neutral,Neutral,Disagree,Agree,Strongly Agree,Strongly Agree,Agree,Strongly Agree
1,Jane Smith,18-24,Female,Middle Eastern,Operations Manager,Sales,2024-10-07,Agree,Strongly Disagree,Strongly Agree,Neutral,Neutral,Disagree,Neutral,Neutral,Neutral,Agree,Neutral
2,Carlos Reyes,45-54,Female,Indian,UX Designer,Consulting,2024-10-08,Neutral,Strongly Disagree,Agree,Disagree,Strongly Agree,Agree,Agree,Strongly Disagree,Neutral,Strongly Agree,Strongly Agree
3,Emily Zhang,35-44,Male,Caucasian,UX Designer,HR,2024-10-07,Neutral,Agree,Agree,Strongly Disagree,Strongly Disagree,Strongly Agree,Agree,Strongly Disagree,Strongly Disagree,Agree,Neutral
4,Michael Johnson,18-24,Female,Caucasian,UX Designer,Product Development,2024-10-07,Agree,Strongly Agree,Disagree,Neutral,Strongly Disagree,Disagree,Disagree,Disagree,Strongly Disagree,Neutral,Disagree
5,Sara Ahmed,45-54,Male,Middle Eastern,Business Consultant,Operations,2024-10-09,Disagree,Strongly Disagree,Neutral,Neutral,Agree,Agree,Disagree,Neutral,Agree,Strongly Disagree,Neutral
6,Tom Davis,25-34,Male,Caucasian,UX Designer,HR,2024-10-08,Strongly Agree,Strongly Agree,Strongly Disagree,Strongly Agree,Strongly Agree,Strongly Disagree,Strongly Agree,Strongly Disagree,Neutral,Neutral,Agree
7,Linda Lopez,18-24,Male,African American,Customer Support,Product Development,2024-10-10,Disagree,Agree,Neutral,Strongly Disagree,Strongly Disagree,Agree,Neutral,Agree,Disagree,Disagree,Agree
8,Raj Patel,35-44,Female,Indian,Product Manager,IT,2024-10-07,Strongly Disagree,Strongly Agree,Strongly Disagree,Agree,Strongly Agree,Agree,Agree,Neutral,Agree,Strongly Agree,Disagree
9,Amara Njeri,18-24,Male,African American,HR Specialist,Design,2024-10-10,Strongly Agree,Strongly Agree,Agree,Agree,Strongly Agree,Strongly Disagree,Neutral,Agree,Neutral,Neutral,Strongly Disagree
10,Helen Martin,45-54,Male,Asian,HR Specialist,Consulting,2024-10-05,Neutral,Neutral,Strongly Disagree,Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Disagree,Disagree,Strongly Disagree,Neutral
11,Peter Brown,18-24,Female,Indian,HR Specialist,Sales,2024-10-12,Strongly Disagree,Disagree,Agree,Strongly Agree,Neutral,Agree,Neutral,Strongly Agree,Neutral,Agree,Agree
12,Nina Roberts,25-34,Female,Middle Eastern,Sales Executive,Sales,2024-10-11,Disagree,Agree,Strongly Disagree,Strongly Disagree,Neutral,Agree,Neutral,Agree,Disagree,Agree,Disagree
13,Jake Williams,18-24,Female,Hispanic,Business Consultant,Sales,2024-10-08,Agree,Strongly Disagree,Strongly Agree,Neutral,Neutral,Neutral,Strongly Agree,Disagree,Neutral,Agree,Strongly Agree
14,Aisha Thompson,18-24,Female,Middle Eastern,Data Analyst,Finance,2024-10-12,Agree,Agree,Strongly Disagree,Strongly Disagree,Disagree,Strongly Disagree,Disagree,Strongly Agree,Disagree,Agree,Strongly Agree

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Name                              15 non-null     object
 1   Age Bracket                       15 non-null     object
 2   Gender                            15 non-null     object
 3   Ethnicity                         15 non-null     object
 4   Job Title                         15 non-null     object
 5   Department                        15 non-null     object
 6   Date Survey Completed             15 non-null     object
 7   Job Satisfaction                  15 non-null     object
 8   Work-Life Balance                 15 non-null     object
 9   Management Support                15 non-null     object
 10  Team Collaboration                15 non-null     object
 11  Workload Fairness                 15 non-null     object
 12  Career Development Opportunities  15 non-null     object
 13  Workplace Inclusivity             15 non-null     object
 14  Company Communication             15 non-null     object
 15  Compensation Satisfaction         15 non-null     object
 16  Job Security                      15 non-null     object
 17  Overall Engagement                15 non-null     object
dtypes: object(18)
memory usage: 2.2+ KB

In [49]:
# df.columns

df.columns= df.columns.str.strip().str.replace(" ","_").str.replace("-","_")

mapping the values

In [50]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()

col=['Job_Satisfaction', 'Work_Life_Balance', 'Management_Support', 
     'Team_Collaboration', 'Workload_Fairness', 'Career_Development_Opportunities', 
     'Workplace_Inclusivity', 'Company_Communication', 'Compensation_Satisfaction', 
     'Job_Security', 'Overall_Engagement']

In [51]:
for columns in col:
    df[columns]=l.fit_transform(df[columns])

In [57]:
df

,Name,Age_Bracket,Gender,Ethnicity,Job_Title,Department,Date_Survey_Completed,Job_Satisfaction,Work_Life_Balance,Management_Support,Team_Collaboration,Workload_Fairness,Career_Development_Opportunities,Workplace_Inclusivity,Company_Communication,Compensation_Satisfaction,Job_Security,Overall_Engagement
0,John Doe,25-34,Female,Asian,Product Manager,Product Development,2024-10-05,1,3,2,2,2,1,0,3,3,0,3
1,Jane Smith,18-24,Female,Middle Eastern,Operations Manager,Sales,2024-10-07,0,4,3,2,2,1,2,2,2,0,2
2,Carlos Reyes,45-54,Female,Indian,UX Designer,Consulting,2024-10-08,2,4,0,1,3,0,0,4,2,3,3
3,Emily Zhang,35-44,Male,Caucasian,UX Designer,HR,2024-10-07,2,0,0,4,4,3,0,4,4,0,2
4,Michael Johnson,18-24,Female,Caucasian,UX Designer,Product Development,2024-10-07,0,3,1,2,4,1,1,1,4,2,1
5,Sara Ahmed,45-54,Male,Middle Eastern,Business Consultant,Operations,2024-10-09,1,4,2,2,0,0,1,2,0,4,2
6,Tom Davis,25-34,Male,Caucasian,UX Designer,HR,2024-10-08,3,3,4,3,3,4,3,4,2,2,0
7,Linda Lopez,18-24,Male,African American,Customer Support,Product Development,2024-10-10,1,0,2,4,4,0,2,0,1,1,0
8,Raj Patel,35-44,Female,Indian,Product Manager,IT,2024-10-07,4,3,4,0,3,0,0,2,0,3,1
9,Amara Njeri,18-24,Male,African American,HR Specialist,Design,2024-10-10,3,3,0,0,3,4,2,0,2,2,4
10,Helen Martin,45-54,Male,Asian,HR Specialist,Consulting,2024-10-05,2,2,4,0,3,3,3,4,1,4,2
11,Peter Brown,18-24,Female,Indian,HR Specialist,Sales,2024-10-12,4,1,0,3,2,0,2,3,2,0,0
12,Nina Roberts,25-34,Female,Middle Eastern,Sales Executive,Sales,2024-10-11,1,0,4,4,2,0,2,0,1,0,1
13,Jake Williams,18-24,Female,Hispanic,Business Consultant,Sales,2024-10-08,0,4,3,2,2,2,3,1,2,0,3
14,Aisha Thompson,18-24,Female,Middle Eastern,Data Analyst,Finance,2024-10-12,0,0,4,4,1,4,1,3,1,0,3

#### `descriptive statistics`

In [67]:
mean = df[col].mean()
mode= df[col].mode().iloc[0].values
medians= df[col].median()
variance= df[col].var()

In [69]:
stats_df= pd.DataFrame({'Mean':mean,'Mode':mode,'Medians':medians,'Variance':variance})

In [70]:
stats_df

                                      Mean  Mode  Medians  Variance
Job_Satisfaction                  1.600000   0.0      1.0  1.971429
Work_Life_Balance                 2.266667   3.0      3.0  2.638095
Management_Support                2.200000   4.0      2.0  2.742857
Team_Collaboration                2.200000   2.0      2.0  2.171429
Workload_Fairness                 2.533333   2.0      3.0  1.266667
Career_Development_Opportunities  1.533333   0.0      1.0  2.695238
Workplace_Inclusivity             1.466667   2.0      2.0  1.266667
Company_Communication             2.200000   4.0      2.0  2.314286
Compensation_Satisfaction         1.800000   2.0      2.0  1.457143
Job_Security                      1.400000   0.0      1.0  2.400000
Overall_Engagement                1.800000   2.0      2.0  1.600000